### ISSUE TITLE
update company-box icons?

### ISSUE THREAD

**Issue by stardiviner** [sebastiencs/company-box#124]
The default `company-box-icons-images` has many duplicated icons.

I suggest to update it. @sebastiencs shared vscode-icons repo. https://github.com/microsoft/vscode-icons
The background discussion here https://github.com/sebastiencs/company-box/pull/115

And here is my thought:

Thanks for pasting the link.

Can company-box display svg directly? Then no need to convert svg image to png. Does it have performance loss if using svg icon?

I checked icons in vscode-icons. I realized except some `symbol-` prefixed coding related icons. There are some icons maybe useful in some cases. So I choosed half of all icons.

Display vscode-icons and select icons side by side:

![image](https://user-images.githubusercontent.com/378699/91648475-e8cf8a00-ea9a-11ea-9e21-df0b63d2e442.png)

Here is a screenshot of selected icons:

![image](https://user-images.githubusercontent.com/378699/91648548-a0649c00-ea9b-11ea-8b44-4b3bd2629013.png)

**Comment by sebastiencs** [comment]
What would be the advantages of using svg files instead of png ? 
I might be wrong but I think displaying svg images requires some flag at compile time and external libraries, whereas png files are built in emacs.

Those icons looks good, I think it would be better to keep the same icons as vscode for `company-box-icons-images`.
