### ISSUE TITLE
cannot see current selected item

### ISSUE THREAD

**Issue by 354651432** [sebastiencs/company-box#176]
uncompany-boxed
![gnome-shell-screenshot-QYB090](https://user-images.githubusercontent.com/8469080/133754930-dd833503-5fbd-498e-87f6-290226e9c139.png)

company-boxed
![image](https://user-images.githubusercontent.com/8469080/133753930-d6b28bfe-088d-4036-ad4d-124eda0ab8c4.png)
current item is `use-package-hush`, but its background hight light is missing

**Comment by acanimal** [comment]
same issue here with emacs 28.2

once installes company-box the selected candidate is not hightlighted

**Comment by dgutov** [comment]
It's probably related to how your theme you're using is defined. It's not the default one, right?

**Comment by Hi-Angel** [comment]
> It's probably related to how your theme you're using is defined. It's not the default one, right?

Well, as a matter of fact it seems to be the default one. I don't see [in my `.emacs` file](https://github.com/Hi-Angel/dotfiles/blob/master/.emacs) anything theme-changing related, except a variable `custom-safe-themes`. IIRC at some point I settled with the default theme, because I disable a number of major-mode font-locks [to make identifiers stand out per this advice](https://github.com/ankurdave/color-identifiers-mode#configuration) anyway.

**Comment by dgutov** [comment]
Hmm, that's unfortunate. I figured this issue only affects a number of people.

Maybe try installing and enabling `company-posframe` instead? And see how it behaves.

If it doesn't have this problem, one could compare the implementations.

**Comment by Hi-Angel** [comment]
> Maybe try installing and enabling `company-posframe` instead? And see how it behaves.

Works, as a matter of fact I see no difference with and without `company-posframe-mode` enabled

> If it doesn't have this problem, one could compare the implementations.

I looked at the code, apparently it has no problem compared to `company-box` because it doesn't `defface` selection face. It only has 6 uses of `defface`, the only interesting ones are `company-posframe-active-backend-name` and same for "inactive", Idk what they're for. But I doubt it's anything related to a completion selection face.

**Comment by dgutov** [comment]
Ah, yup. I forgot that `company-box` has its own set of faces. Not sure why it needs a separate set.

**Comment by Hi-Angel** [comment]
> ```lisp
> (set-face-attribute 'company-box-selection nil :background "light blue")
> ```

Right, as I mentioned in [the first comment](https://github.com/sebastiencs/company-box/issues/176#issuecomment-1406623274), the problems comes to it inheriting the face which is somehow broken. But overriding the face directly like a `(set-face-attribute 'company-box-selection nil :background "light blue")` makes it work.

**Comment by Hi-Angel** [comment]
> Ah, yup. I forgot that `company-box` has its own set of faces. Not sure why it needs a separate set.

Right, as I mentioned in [the first comment](https://github.com/sebastiencs/company-box/issues/176#issuecomment-1406623274), the problems comes to it inheriting the face which is somehow broken. But overriding the face directly like a `(set-face-attribute 'company-box-selection nil :background "light blue")` makes it work.

**Comment by Hi-Angel** [comment]
So, I sent a PR that fixes the `company-box` problem.

Basically, the problem was that the plugin was using its own face before actually declaring them. IMO this should've raised a runtime error, but for some reason it didn't, and just resulted in a silent bug.
