### ISSUE TITLE
Company-Box causes EMACS to freeze and slow to respond, never actually displays any completions. 

### ISSUE THREAD

**Issue by anoduck** [sebastiencs/company-box#192]
Since installing company-box, I have lost the company dropdown menu, and company appears to have stopped functioning altogether. Emacs freezes all together when asked to perform a completion, and is in general slow to respond. Since installing, I have yet to actually see a completion box dropdown.

**Comment by Hi-Angel** [comment]
Please post a minimal reproducible example, otherwise it's impossible to debug the problem. I installed it yesterday, has used for a bit and so far [except this problem](https://github.com/sebastiencs/company-box/pull/193) haven't found any. And mind you, I have `company-idle-delay` set to `0.2`, so completion appears almost immediately if available.

**Comment by Hi-Angel** [comment]
By any chance, aren't you're using Emacs from a terminal? The plugin README says

> not compatible with emacs in a tty

Idk if the plugin added detection of such situation or simply glitches out

**Comment by anoduck** [comment]
I am going to close this one out, since the issues that I was experiencing have apparently disappeared. Several things have changed in my `init.el`, and it appears it was for the better. 

Now, if only I could discover a dark Emacs color theme with high contrast, that appeals to me.
